# Generated by Django 5.2.7 on 2025-10-27 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('niveau', models.CharField(max_length=50)),
                ('filiere', models.CharField(max_length=100)),
                ('capacite_max', models.PositiveIntegerField(default=20)),
                ('etudiants', models.ManyToManyField(blank=True, limit_choices_to={'role': 'ETUDIANT'}, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
